### ISSUE TITLE
비지니스 로직구현 Domain VS Service

### ISSUE THREAD

**Issue by songks0922** [Java-Chip4/StudyingRecord#23]
비지니스 로직을 Entity에 구현하는 것이 맞는지 Service 계층에 구현하는게 맞는지 의문입니다. 도메인 모델 패턴을 사용하게 되면 객체 지향의 특성을 살릴 수 있다는 장점이 있겠지만 그렇다면 Service 계층에서는 어떤 역할을 해야하는지 단순히 도메인에 구현 해놓은 비지니스 로직을 위임하는 정도로 사용하는 것인지 궁금합니다. 기본적으로 Service 계층에서 해줘야 하는 일이 무엇일까요?

**Comment by songks0922** [comment]
https://www.inflearn.com/questions/117315

**Comment by anthologia** [comment]
https://www.inflearn.com/questions/250279
https://www.inflearn.com/questions/13362
https://www.inflearn.com/questions/146139

질문 찾아보다가 추가적인 답변이 있어서 덧붙여요.

더불어서 도메인 모델에 관한 글도 하나 올리고 갑니다. 🏃‍♂️
https://javacan.tistory.com/entry/what-is-a-domain-model
