### ISSUE TITLE
WAS와 Web Server의 차이와 각각의 역할

### ISSUE THREAD

**Issue by songks0922** [Java-Chip4/StudyingRecord#29]
이번강의 섹션1에 HTML, HTTP API, CSR, SSR 여기서 WAS가 언급되는데 Web Server와의 차이가 무엇인지 WAS만으로 서비스를 할 수 있는건지 궁금합니다. 각각의 용어 정의를 한번 해보면 좋을거같아요.

**Comment by KimChanJin97** [comment]
![1](https://user-images.githubusercontent.com/102044895/190990281-a2ba0467-c6a0-447c-ab78-aa24a6e7edf6.png)

용어 정리

**HTTP API**
- HTTP methods 를 사용해 데이터를 전달
- WAS가 DB에 접근해 데이터를 GET, POST, DELETE 함
- 데이터는 주로 JSON 형식
- 웹클라이언트<->WAS / 앱클라이언트<->WAS / WAS<->DB
- 사용자에게 데이터를 보여줘야 하므로 UI 클라이언트 접점

**CSR(Client Side Rendering)**
- WAS(서버)가 아닌 웹브라우저에서 HTML을 생성하여 적용
- HTML (내용X, 자바스크립트 링크)
- 자바스크립트 (클라이언트 로직, HTML 렌더링코드)
- HTTP API (주로 JSON형태)
- 동적인 화면에 사용
- 웹 프론트엔드 파트

**SSR(Server Side Rendering)**
- WAS(서버)에서 최종 HTML을 생성해서 클라이언트에게 전달
- 정적인 화면에 사용
- 백엔드 파트 

**Servlet**
- 웹클라이언트로부터 HTTP 요청메시지가 들어오면 WAS(서버)가 HTTP 요청메시지를 보고 Request객체와 Response객체를 만든다. 이 객체들을 Web Container(또는 Servlet Container)에서 관리하는데, 이 객체들을 '서블릿'이라고 한다. 

**WAS (Web Application Server)**
- WAS = Web Server + Web Container(또는 Servlet Container)
- 중요한 애플리케이션 로직 처리 전담

**Web Server**
- 정적 리소스 처리 담당
- 애플리케이션 로직같은 동적인 처리가 필요하면 WAS에 요청을 위임

**Web Container(Servelet Container)**
- 웹서버와의 통신 지원
- 서블릿들의 생성, 실행, 파괴를 담당
- 멀티쓰레드 지원 및 관리
- 선언적인 보안 관리


**WAS 만으로 서비스를 할 수 있을까?**
WAS 가 Web Server 를 포함하고 있기 때문에 가능하다고 생각합니다.

**Comment by anthologia** [comment]
강의에서는
- Servlet(1997) -> JSP(1999) -> MVC Pattern(Servlet + JSP) -> MVC Framework(2000)
- JSP -> Freemarker / Velocity -> Thymeleaf

순서로 변화왔다고 했는데요.

그러면 현재 기준으로 Spring MVC와 Thymeleaf는 사진 상으로 WAS의 Web Container에 담겨 있다고 봐야 하는 걸까요?

**Comment by songks0922** [comment]
https://codechasseur.tistory.com/25
> WAS는 DB 조회 및 다양한 로직을 처리하는 데 집중해야 한다. 따라서 단순한 정적 컨텐츠는 웹 서버에게 맡기며 기능을 분리시켜 서버 부하를 방지한다.  만약 WAS가 정적 컨텐츠 요청까지 처리하면, 부하가 커지고 동적 컨텐츠 처리가 지연되면서 수행 속도가 느려지고 이로 인해 페이지 노출 시간이 늘어나는 문제가 발생하여 효율성이 크게 떨어진다.
따라서 서버의 부하를 줄이기 위해서 WAS와 Web Server는 같이 사용하는 것이 맞다는 얘기가 써있네요
