### ISSUE TITLE
AppConfig 파일에 적용된 GRASP 패턴

### ISSUE THREAD

**Issue by songks0922** [Java-Chip4/StudyingRecord#3]
creator 패턴이 적용되어 있는데 이것이 무엇인지 이로 인해 얻는 이점은 무엇인지 토의해보면 좋겠습니다.

**Comment by KimChanJin97** [comment]
**Creator
 :  A객체를 포함하거나 기록하는 B객체가 A객체를 생성할 책임이 있다는 원칙**
**A 객체와 B 객체의 관계의 관계가 다음 중 하나라면 A의 생성을 B의 책임으로 부여.**
경우1. B 객체가 A 객체를 포함하고 있다.
경우2. B 객체가 A 객체의 정보를 기록하고 있다.
경우3. A 객체가 B 객체의 일부이다.
경우4. B 객체가 A 객체를 긴밀하게 사용하고 있다.
경우5. B 객체가 A 객체의 생성에 필요한 정보를 가지고 있다.


**// hello.core.member.MemberServiceImpl**
```
package hello.core.member;

public class MemberServiceImpl implements MemberService {
    private final MemberRepository memberRepository;

    public MemberServiceImpl(MemberRepository memberRepository) {
        this.memberRepository = memberRepository;
    }
      ... (실행)
}
```


**// hello.core.AppConfig**
```
public class AppConfig {
    public MemberService memberService() {
        return new MemberServiceImpl(new MemoryMemberRepository());
    }
      ... (실행)
}
```
**hello.core.AppConfig** 에서
- new 키워드로 MemoryMemberRepository() 생성자 호출, 객체 생성
- new 키워드로 MemberServiceImpl() 생성자 호출, 객체 생성 + 앞서 생성했던 객체 주입
- MemberServiceImpl() 생성자의 인자에 MemoryMemberRepository() 생성자를 주입한다는 것을
- MemberServiceImpl() 객체가 MemoryMemberRepository() 객체를 포함한다고 볼 수 있다. 이는 creator 패턴의 경우1 에 해당한다고 볼 수 있다. (내 생각...)



- creator 패턴을 적용함으로써 얻는 이득을 구현체와 AppConfig로 구분해서 정리하자면
**hello.core.member.MemberServiceImpl** 에서
- 첫번째 이득. MemberServiceImpl는 의존관계에 대한 고민은 외부(AppConfig)에 맡기고 실행(...부분)에만 집중할 수 있음!
- 두번째 이득. OrderServiceImpl 클래스가 더 이상 인터페이스와 구현체 모두에게 의존하지 않고 인터페이스에만 의존할 수 있다. 즉, DIP을 지킬 수 있다는 것이다
- 세번째 이득. 만약 OrderServiceImpl 클래스가 인터페이스와 구현체 모두에게 의존하는 상황이었더라면 구현체 생성자를 변경해야 했을 경우 구현체 생성자를 변경해야 했을 것이다. 이는 OCP를 위반하는 상황이다. 그래서 creator 패턴을 적용한다면 다시말해, OrderServiceImpl 클래스가 인터페이스에만 의존한다면 OCP를 지킬 수 있다는 것이다. 
**hello.core.AppConfig** 에서
- 첫번재 이득. MemberServiceImpl 생성자를 통해 어떤 구현체를 주입할지는 오직 외부(AppConfig)에서 결정! OCP를 지킬 수 있다.

**Comment by songks0922** [comment]
김영한님이 역할과 책임의 분리를 강조하시는데 Creator 패턴을 적용해서 객체를 생성하는 책임을 해당 클래스에 할당한다고 보면 되겠습니다. General Responsibility Assignment Software Patterns(GRASP) 책임을 할당하는 소프트웨어 패턴
