### ISSUE TITLE
@Component와 @Component에서 파생된 애노테이션의 차이

### ISSUE THREAD

**Issue by anthologia** [Java-Chip4/StudyingRecord#41]

**Comment by songks0922** [comment]
https://stackoverflow.com/questions/6827752/whats-the-difference-between-component-repository-service-annotations-in

**Comment by jooyoungg** [comment]
스프링은 간편한 스프링 빈 등록을 위해 `@Component` 어노테이션을 지원한다. 그러나 동일한 동작을 하는 `@Repository`, `@Controller`, `@Service` 어노테이션도 존재한다. 세 어노테이션 간의 차이점은 무엇이고, 왜 사용해야 하는 걸까?

![images_guri_coding_post_182960c1-54e3-4095-88a1-9f9747666f62_@component 구조](https://github.com/SpringStudyInf/spring-is-comming/assets/132862228/02de0af7-ff54-4070-b0ec-e86dbb31a39e)

먼저, [스프링 공식 문서](https://docs.spring.io/spring-framework/reference/core/beans/classpath-scanning.html#beans-stereotype-annotations)를 찾아보았다. 여기서 하는 말은 다음과 같다.
> ### `@Component` and Further Stereotype Annotations
> The @Repository annotation is a marker for any class that fulfills the role or stereotype of a repository (also known as Data Access Object or DAO). Among the uses of this marker is the automatic translation of exceptions, as described in [Exception Translation](https://docs.spring.io/spring-framework/reference/data-access/orm/general.html#orm-exception-translation).
> 
> Spring provides further stereotype annotations: @Component, @Service, and @Controller. @Component is a generic stereotype for any Spring-managed component. @Repository, @Service, and @Controller are specializations of @Component for more specific use cases (in the persistence, service, and presentation layers, respectively). Therefore, you can annotate your component classes with @Component, but, by annotating them with @Repository, @Service, or @Controller instead, your classes are more properly suited for processing by tools or associating with aspects. For example, these stereotype annotations make ideal targets for pointcuts. @Repository, @Service, and @Controller can also carry additional semantics in future releases of the Spring Framework. Thus, if you are choosing between using @Component or @Service for your service layer, @Service is clearly the better choice. Similarly, as stated earlier, @Repository is already supported as a marker for automatic exception translation in your persistence layer.

- `@Component`
  - 단순히 스프링 빈을 등록하는 역할 수행
- `@Repository`, `@Service`, `@Controller`
  - `@Component` 라는 공통점을 가지는 어노테이션으로 `@Component`의 특수하고 정형화된 상황에 사용
    - 명시적으로 해당 클래스가 어떤 기능을 수행하는지 암시
    - 향후 스프링 프레임워크에 해당 어노테이션에 대한 신규 기능이 추가될 경우 수정 용이

---
### `@Controller`
- Presentation layer에서 Controller를 명시하기 위해 사용
  - 브라우저상의 웹 클라이언트의 요청 및 응답을 처리
  - 서비스계층, 데이터 엑세스 계층에서 발생하는 Exception을 처리
- WebMVC를 사용할 수 있도록 `@RequestMapping`, `@GetMapping`과 같은 URI 요청 어노테이션을 제공

### `@Service`
- Business layer에서 Service를 명시하기 위해 사용
  - 애플리케이션 비즈니스 로직 처리와 비즈니스와 관련된 도메인 모델의 적합성 검증
  - Presentation layer와 Persistence layer 사이를 연결하는 역할로 두 계층이 직접적으로 통신하지 않게 함
    - 확장성과 재사용성 그리고 중복 코드의 제거를 위함
    - 비즈니스 로직은 타 컨트롤러에서 중복 사용이 요구될 수도 있다. 만약, 비즈니스 로직 코드가 컨트롤러에 구현되어 있다면, 코드 중복이 발생한다.
    - 모든 기능을 세분화하여  `@Service`에 작성한다면, 향후 서비스의 기능들을 조합하여 새로운 기능으로 확장 가능.
- 현재는 `@Component`와 다른 기능은 없다.

### `@Repository`
- Persistence layer에서 DAO를 명시하기 위해 사용
  - DB에 CRUD를 수행
- 스프링 프레임워크에서 지원하지 않는 낮은 레벨의 persistence exception(checked exception)을 높은 레벨의 spring exception인 DataAccessException 으로 변환
  - 로우레벨의 예외를 좀 더 의미 있고 추상화된 예외로 변경
  - 이로 인해, checked exception을 unchecked exception 즉, 런타임 예외로 감싸 어차피 복구가 불가능한 SQLException에 대한 불필요한 catch/throws 축소
    - SQLException의 throws는 정말 최악인 것이 DAO 밖으로 던져도 할 수 있는 것이 없기 때문이다.
    - DataAccessException 발생시, `@Transactional` 이 있다면 스프링 프레임워크에서 DB 롤백을 진행해준다.


![img1 daumcdn](https://github.com/SpringStudyInf/spring-is-comming/assets/132862228/b591ba96-90e8-4964-8b4a-dd462b790671)


---
참고
- https://medium.com/webeveloper/spring-mvc-architecture-236235d48fa1
- https://gmlwjd9405.github.io/2018/12/25/difference-dao-dto-entity.html
- https://hamcheeseburger.tistory.com/entry/Component-Controller-Service-Repository%EC%9D%98-%EC%B0%A8%EC%9D%B4
- https://jongmin92.github.io/tags/DataAccessException/
- https://stackoverflow.com/questions/7125837/why-does-transaction-roll-back-on-runtimeexception-but-not-sqlexception
- https://www.javacodegeeks.com/2017/11/difference-component-service-controller-repository-spring.html
