### ISSUE TITLE
Logger의 성능과 별도 저장 방법

### ISSUE THREAD

**Issue by anthologia** [Java-Chip4/StudyingRecord#51]
1. 로그를 사용해야 하는 이유의 하나로 **`System.out` 보다 성능이 좋기 때문**이 있었습니다.
얼마나 더 좋고, 왜 더 좋은가요?

2. 로그를 파일 혹은 네트워크 등 별도의 위치에 저장할 수 있다고 합니다. 저는 아직 로그를 사용해 본 적이 없는데요. 어떻게 저장을 할 수 있는지 알아보면 좋을 것 같아요.

**Comment by rkdtmddnjs97** [comment]
1. 어떤 블로거가 Logback 이전에 apache 기반의 log4j와 logback 라이브러리의 성능 비교를 한 포스트가 있는데요, System.out이 로그는 아니라서 성능 비교가 달라지겠지만 참고를 해서 얼마나 더 좋은지 테스트를 하는게 좋을 것 같습니다.
https://xlffm3.github.io/spring%20&%20spring%20boot/async-logger-performance/
그리고 로깅이 왜 좋은지는 여러 이유가 있는데요.  `` System.out`` 은 말그대로 콘솔창에 어떤 데이터를 찍는 것이기 때문에  휘발되는 데이터입니다. 어딘가에 저장하려면 다른 작업이 필요하죠. 그리고 log도 warning인지 error 인지 단계가 있고 또 추가적인 기능에 대한 수동 작업을 해줘야 합니다. 하지만 log 라이브러리는 제공해주는 기능들이 더 많기 때문에 장점이 더 많습니다.

2. logback 기준으로 log를 저장하는 방식은 xml 설정으로  가능한 것 같습니다.
https://velog.io/@rivernine/Spring-boot-Logback%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-%EB%A1%9C%EA%B7%B8%EC%A0%80%EC%9E%A5
