### ISSUE TITLE
python decorator 와 java annotation의 차이

### ISSUE THREAD

**Issue by songks0922** [Java-Chip4/StudyingRecord#7]

**Comment by anthologia** [comment]
### Python decorator와 Java Annotation의 차이
Python decorator와 Java annotation의 차이는 두 언어를 동시에 다루고 있는 사람이라면, 한 번쯤은 고민해볼만한 내용입니다.

___

#### Python decorator

먼저, 데코레이터 디자인 패턴에 대해 짧게 다루고 싶습니다.

> 데코레이터 패턴은 wrapper 객체 내에 새로운 객체를 배치하여 구현을 변경하지 않고도 객체에 새로운 동작을 동적으로 추가할 수 있도록 합니다.

즉, 기존 코드를 변경하지 않고도, 새로운 행동을 할 수 있도록 덧붙여주는 것입니다.
(https://gdtbgl93.tistory.com/9)

이 데코레이터 패턴은 여러 곳에서 상당히 유용하게 사용되고 있습니다.
그래서 Python에서는 이를 문법적으로 지원하기 위해 언어적 차원에서 decorator를 만들었습니다. 

Python docs에서는 decorator를 다음과 같이 설명합니다.

> decorator는 한 함수를 @wrapper 문법을 통해 다른 함수로 반환하며, 일반적으로 classmethod()와 staticmethod()에 사용됩니다.
> 이는 그저 단순히 문법적으로 지원하는 편리성일뿐, 두 함수의 정의는 의미으로 동등합니다.

```
def f(arg):
...
f = staticmethod(f)

@staticmethod
def f(arg):
...
```

(https://docs.python.org/3/glossary.html)

___


#### Java Annotation

Oracle Java 문서에서는 Annotation에 대해 다음과 같이 정의합니다.

> 메타데이터의 한 형태인 어노테이션은 프로그램에 대한 데이터를 제공합니다. 어노테이션은 자신이 @Annotation을 단 코드의 작동에 직접적인 영향을 미치지 않습니다.

(https://docs.oracle.com/javase/tutorial/java/annotations/index.html)

실제로 우리가 Java에서 자주 사용하는 어노테이션으로는 무엇이 있을까요?
@Override 가 있습니다. 이는 컴파일러에게 메서드에 대한 정보를 전달해주는 사례입니다.

다음으로는, 스프링 프레임워크에서 사용되는 어노테이션의 사례를 보겠습니다.
```
@RequestMapping(
    value = "/hello", method = GET)
@ResponseBody
public String getHelloMessage() {
    return "hello";
}
```
이는 클라이언트가 GET method로 /hello에 접근하는 것을 잡아내는 역할을 합니다.

그런데 Java 어노테이션의 정의에서는 메타 데이터를 전달하기만 할 뿐, 코드의 작동에 영향을 미치지 않는다고 했는데요.
@RequestMapping은 코드의 작동에 영향을 미치는 것으로 보입니다.

그 외에도, 스프링에서 AOP를 구현할 때, 어노테이션을 활용하는데, 이때 역시 코드의 작동에 영향을 미칩니다.

이게 무슨 일일까요?

사실, Oracle Java 문서에서는 어노테이션이 다음과 같이 사용될 수 있다고 했습니다.

> - 컴파일러에게 정보 전달에 사용 : 어노테이션은 컴파일러에게 오류 검출 혹은 경고 무시에 대한 지시를 내릴 때 사용될 수 있습니다.
> - 컴파일 타임과 개발 과정에 사용 : 소트트웨어 툴은 어노테이션 정보를 사용하여 코드, XML 파일 등을 생성할 수 있습니다.
> - 런타임에 사용 : 몇몇 어노테이션은 런타임시 활용될 수 있습니다.

스프링 프레임워크에서는 Java 어노테이션을 활용하여 여러 기능 코드를 추가하여 활용하고 있습니다.
우리 역시 커스텀 어노테이션을 작성하여 사용할 수도 있죠. 
* 커스텀 어노테이션 : (https://mangkyu.tistory.com/130)

즉, Java 어노테이션을 활용하여 Python decorator와 같이 사용할 수는 있지만, Java 어노테이션 그 자체만으로는 불가능하다는 것입니다.

(https://medium.com/@dmytro.de/pythons-decorators-vs-java-s-annotations-same-thing-2b1ef12e4dc5)
(https://stackoverflow.com/questions/15347136/is-a-python-decorator-the-same-as-java-annotation-or-java-with-aspects)
