### ISSUE TITLE
static 멤버로만 구성된 클래스 VS. 싱글톤 클래스

### ISSUE THREAD

**Issue by charlesuu** [Java-Chip4/StudyingRecord#8]
> 스프링 핵심 원리 기본편 : 싱글톤 패턴[00 : 31]

질문 : 
1. `static 멤버로만 구성된 클래스`와 `싱글톤 클래스` 간에 어떤 차이점이 있나요?, 
2. 둘 중에 싱글톤을 더 많이 쓰는 이유가 뭘까요?

 강의를 통해 싱글톤 패턴이 어떤 상황에서 쓰이는지 배웠습니다.
요청이 올 때마다 새로운 객체를 만드는 대신, 이미 존재하는 하나의 객체가 모든 요청을 처리하게 했습니다.
이를 통해 불필요한 메모리 낭비를 없앴죠.

 싱글턴으로 구현하는 대신, 모든 멤버 변수 및 메서드가 static인 클래스를 만들었어도 똑같은 장점을 누릴 수 있을거라는 생각이 들었습니다. 굳이 객체를 만들어서 동작하게 하지 않고, 클래스 멤버를 통해서 동작하게 하는거죠.

 강의 속 예제에 한정하면 두 방식 사이에 아무런 차이가 없을 것 같습니다. 실제로는 두 방식 간에 어떤 차이점이 있나요? 싱글톤을 더 많이 쓰는 이유는 뭘까요? ~~다형성??~~

**Comment by songks0922** [comment]
싱글톤 패턴 예제 보면 static 멤버로 이루어져 있는거 같은데요? 그리고 Thread safe 문제도 발생할 것 같습니다. race condition이 있을 경우 의도한 대로 작동하지 않을 가능성이 있거든요.
https://cjw-awdsd.tistory.com/42
